### PR TITLE
Add GHA build

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/gliptak/jurity/actions/runs/1182867366

### CODE REVIEW

**Comment by dorukkilitcioglu** [comment]
Hi @gliptak, thank you for your contribution and your interest in Jurity! As it stands, this GHA only installs Jurity on an Ubuntu system. Can you give some more information on how this can be used and why it's important to have this action set up? If there are any examples of this in well-known repos, that would also be great to look at.

**Comment by gliptak** [comment]
@dorukkilitcioglu number of Fidelity's repos use GHA

https://github.com/fidelity/kconnect
https://github.com/fidelity/awsrun

As currently configured, all PRs are validated by running `install` (including running testcases as applicable). Additional tasks can also be configured based on project specifics.

**Comment by dorukkilitcioglu** [comment]
Thanks @gliptak. As you mentioned, running unit tests would be better in terms of validating any PRs. Could you update the PR to run the unit tests as well, as I don't think they're covered by the `install`? Once that's added we can also add a test coverage badge like [here](https://github.com/fidelity/spock).

I'd also add Python versions 3.6 and 3.7 to the Python versions as Jurity is meant to be compatible with Python 3.6+.

**Comment by gliptak** [comment]
@dorukkilitcioglu current codebase fails to install with `Python 3.6`

https://github.com/gliptak/jurity/pull/1/checks?check_run_id=3476788963

**Comment by dorukkilitcioglu** [comment]
@gliptak I believe the issue is with installing the library using `python setup.py install`, as it might not be pulling the dependencies correctly. If you change it to a pip install like [here](https://github.com/fidelity/spock/blob/master/.github/workflows/python-lint.yaml#L31-L32) I believe this problem would be gone.

That being said, I can now see how this can be useful, so I'm inclined to accept the PR once this issue gets resolved. I would prefer to also have testing though. @filip-michalsky @skadio @bkleyn what do you think?

**Comment by skadio** [comment]
@gliptak thank you for this nice addition! It help improve our workflow

**Comment by gliptak** [comment]
@dorukkilitcioglu build is green at this point https://github.com/gliptak/jurity/actions/runs/1190278604

**Review by dorukkilitcioglu — APPROVED** [review]
Thanks for the updates, this version looks good to me. I'll let others chime in as well.

**Review by bkleyn — APPROVED** [review]

**Pull request merged**
